name "blom-couchbase"
version "0.1.0"
author "Ørjan Blom"
project_page "https://github.com/blom/puppet-couchbase"
source "https://github.com/blom/puppet-couchbase"
license "ISC"
summary "Couchbase module"
description "Couchbase module"
dependency "puppetlabs/apt", "1.1.0"
dependency "puppetlabs/stdlib", "3.2.0"
